name:                exchange
version:             0.1.0.0
github:              "githubuser/exchange"
license:             MIT
author:              "Stephen Feria"
maintainer:          "stephen.feria003@gmail.com"
category:            Finance

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/exchange#readme>

dependencies:
- base >= 4.7 && < 5
- amqp
- text
- bytestring
- time
- containers
- stm
- pqueue
- aeson
- network-simple

source-dirs:
  - src

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
  ImportQualifiedPost
  DeriveGeneric
  OverloadedStrings

executables:
  exchange-exe:
    main:                exchange.hs 
    source-dirs:         driver
